"""Created contact-form table

Revision ID: a105c0f7f2fd
Revises: a0c6a7c884fa
Create Date: 2020-06-22 19:07:52.852823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a105c0f7f2fd'
down_revision = 'a0c6a7c884fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact-form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=140), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact-form_email'), 'contact-form', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact-form_email'), table_name='contact-form')
    op.drop_table('contact-form')
    # ### end Alembic commands ###
